#!/bin/bash


_hell_telethon () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtVC9iZXRhL21hc3Rlci56aXA=" | base64 -d
}

_hell_pyrogram () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtUC9iZXRhL21hc3Rlci56aXA=" | base64 -d
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHell
    else
        python3 -m TelethonHell
    fi
}

_starter () {
    local hellpath
    hellpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"

    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then
        wget -q $(_hell_pyrogram) -O "$hellpath"
    else
        wget -q $(_hell_telethon) -O "$hellpath"
    fi

    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH

    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HELLBOT •••"

    _library
}

_starter