#!/bin/bash


_hell_zip () {
    git_rex="(https?)://github.com/.+/.+"
    if [[ $GIT_REPO =~ $git_rex ]]
    then
        if [[ $GIT_BRANCH ]]
        then
            echo "${GIT_REPO}/archive/${GIT_BRANCH}.zip"
        else
            echo "${GIT_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZS1IZWxsQm90L1BsdWdpbnMtVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_starter () {
    local hellpath
    hellpath="Plugins.zip"
    echo "••• DOWNLOADING HELLBOT •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH

    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING HELLBOT •••"
    python3 -m TelethonHell
}

_starter
